### PR TITLE
Update ESLint config to 1.0.0. compatibility

### PR DESCRIPTION
**Pull request by anselmbradford**
Updates ESLint config for compatibility with ESLint 1.0.0.

## Additions

- Adds `restParams: true` to ESLint config, to allow use of ...rest syntax.
- Adds `experimentalObjectRestSpread: false` to ESLint config.
- Adds `qunit: false` to environments.
- Adds `serviceworker: true` to environments to support use of serviceworker API.
- Adds `embertest: false` to environments.
- Adds new rules: `no-implicit-coercion`, `no-invalid-this`, `no-param-reassign`, `no-useless-call`, `callback-return`, `id-length`, `id-match`, `arrow-parens`, `arrow-spacing`, `no-class-assign`, `no-const-assign`, `prefer-spread`, `prefer-reflect`, `require-yield`.

## Removals

- Removed deprecated `no-reserved-keys` rule.

## Changes

- Changes `phantomjs` environment to `false` since this should be overridden if needed in a test directory eslintrc file.

## Review

- @wpears 
- @mistergone 
- @ascott1

### CODE REVIEW

**Comment by ascott1** [comment]
@anselmbradford I'm super appreciative of you for keeping up with this. Thank you!

**Comment by Scotchester** [comment]
We gotta keep the grunt-eslint dependency updated in generator-cf, too. Newly-generated projects currently can't build due to it being updated.

**Comment by anselmbradford** [comment]
Yeah, generator-cf should be pegged against a version of this file, not the latest.

**Comment by Scotchester** [comment]
Maybe it would be simpler to just keep this file in the generator?

**Comment by ascott1** [comment]
> Maybe it would be simpler to just keep this file in the generator?

This isn't a bad idea. We could certainly link directly to it from here.

**Pull request merged**
