### PR TITLE
Edits JS code comments block

### PR DESCRIPTION
**Pull request by anselmbradford**
Edits the JS comments section in the playbook to fix formatting/grammar and adds section about JSDocs. 

## Additions

- Creates comments section sub-sections and adds note about JSDocs.

## Changes

- Discourages same-line comments.
- Proper grammar in comments.

## Review

- @ascott1 
- @wpears 
- @mistergone

### CODE REVIEW

**Comment by anselmbradford** [comment]
How's this PR looking?

**Comment by contolini** [comment]
:+1: Nice and straightforward.

**Comment by Scotchester** [comment]
Sorry I'm late on this, but I like same-line comments when the comment only applies to a single line. Are we taking an official stance on this?

**Comment by contolini** [comment]
I avoid same-line comments because Idiomatic [prohibits them](https://github.com/rwaldron/idiomatic.js/#end-of-line-comments-are-prohibited). They also tend to make lines really long.

**Comment by Scotchester** [comment]
True. I would only want to allow them in cases where the line doesn't go over 80 characters.

**Comment by contolini** [comment]
This strikes me as a *it's-fine-to-break-this-rule-just-be-consistent-within-your-codebase* scenario.

**Comment by Scotchester** [comment]
Sounds good to me.

**Comment by contolini** [comment]
We need a tag for that. `IFTBTRJBCWYC`

**Pull request merged**
