### PR TITLE
add eslint file

### PR DESCRIPTION
**Pull request by ascott1**
This adds our recommended ESLint file.

## Review

- @anselmbradford 
- @wpears 
- @mistergone

### CODE REVIEW

**Comment by anselmbradford** [comment]
A few comments (and sorry not to have put these sooner in https://github.com/cfpb/front-end/issues/15!):

- Enforce `comma-dangle`. It's needed for IE8- (when not in IE8 document mode) support.

- Enforce or warn `no-debugger`, since `no-console` is included (I'd lean toward enforcing `no-debugger`).

- Consider adding at least warning-level `valid-jsdoc` flag to flag undocumented code.

- In general I think many of the _Possible Errors_ flags could be enforced. There doesn't seem to be strong reasons not to follow the rules in that section.

- `camelcase` has a `properties` option for checking camelCase of properties of object literals (`always` or `never`). You may want to consider enabling this option (if it's not on by default) and possibly relaxing this rule to a warning. There may be cases when using a third-party API that uses underscores to keep the format the same for areas where the code intersects. I'm not sure, I'm on the fence with this one.

- Enforce or warn `no-catch-shadow`. This is needed for IE8- support. This should only be turned off if we organization-wide want to drop IE8 support.

- Relax `no-extra-parens` to a warning. For instance, in `(a * b) + c` the parentheses may not be necessary, but arguably they make the order of operations clearer and it may be preferred in some cases to retain them for readability of the code.

- Consider relaxing `block-scoped-var` to a warning. This is to help those who don't understand that variables are hoisted in JavaScript. However, for this sort of rule that is meant to guide the programmer toward understanding the behavior of JS I think a warning is sufficient, and those that do understand hoisting may prefer to program in a style that takes hoisting into account.

- Consider relaxing `no-mixed-requires` to a warning and add `true` for the grouping flag to provide warnings about grouping of modules. I'm less familiar with this one, but for ordering of variables it seems like a warning and including the groupings would be more beneficial than strict enforcement without flagging the groupings (while strict enforcement with the groupings seems like overkill).

- Enforce `new-cap`. Do we have conventions for not requiring uppercase for constructor functions? Since constructors in JS look exactly like other functions, but are expected to be used with the `new` keyword elsewhere, I think enforcing a style of a capitalized function name makes sense for clarity.

- `no-space-before-semi` is deprecated in favor of `semi-spacing`.

- I'm in favor of listing out all the rules ESLint provides and setting the rule enforcement flag to zero for the ones we don't want. I know [it seems like a lot](https://github.com/cfpb/cfgov-refresh/blob/flapjack/_settings/eslint.yaml), but I see no reason why this file needs to be succinct at the cost of explicit documentation.

  The actual practical reason for this is the following: Take a project that builds on the base standard and adds additional project-level rules. A diff between that project's eslint file and the standard's would be more complicated because the line-count would be different. However, if both the standard and the project displayed all options available it would be easy to highlight the enforcement flag differences in a diff.

  For example, if a rule was added and a rule was changed **without** all rules listed, the diff looks like:

  screen shot 2015-03-30 at 12 46 11 pm

  ...versus a rule added and changed **with** all rules listed:

  screen shot 2015-03-30 at 12 46 37 pm

  Additionally, it seems clearer to me what rules are being added as some defaults may otherwise be hidden. Also, in the case of ESLint adding a new rule, it makes it clearer whether the rule was omitted because it was not wanted—or whether it was overlooked.

**Comment by anselmbradford** [comment]
Another thing you may want to add is a warning-level rule for `no-warning-comments` (perhaps of `todo`, `fixme`, `xxx`), so that todo style code comments are highlighted before going to production.

**Comment by wpears** [comment]
:+1: :rocket:  :+1:

**Comment by ascott1** [comment]
@anselmbradford :clap:

**Comment by ascott1** [comment]
@anselmbradford I noticed that the [cfgov-refresh ESLint file](https://github.com/cfpb/cfgov-refresh/blob/a8983493d855a042cc8db58c465284da056d6992/_settings/eslint.yaml) is really verbose and well commented. Does it cover all of the rules above? I'd love to use your version rather than the one I have in this PR.

**Comment by anselmbradford** [comment]
@ascott1 It should be update-to-date with ESLint 0.18.0 per updates made in https://github.com/cfpb/cfgov-refresh/pull/442.

I'd suggest this adjustment for a standards ESLint file:
Change code comments to describe the rule when it's enforced, not the current state of the rule. Meaning change `Warn`, `Allow `, etc., e.g. change:

```
# Warn when declaring variables already declared in the outer scope.
```

...into...

```
# Disallow declaring variables already declared in the outer scope.
```

I'll be doing that in cfgov-refresh and could reference the PR here if that works?

**Comment by ascott1** [comment]
:+1: I'm going to update the ESLint file here to reflect yours. Once this is merged I'll update the cf-generator file as well.

**Comment by ascott1** [comment]
The above commit adds @anselmbradford's verbose ESLint file. If we're all happy with this, let's merge!

@anselmbradford @wpears @mistergone

**Comment by wpears** [comment]
I'm sooooo confident Chuck will agree to this awesomeness: :boom: merged:boom:

**Comment by ascott1** [comment]
:heart: @wpears

**Pull request merged**
