### PR TITLE
Adds commonjs module structure guidance

### PR DESCRIPTION
**Pull request by anselmbradford**
I thought it might be helpful to add some guidance on structuring commonJS modules so I threw this doc together with the best practices I'm familiar with. What do you think?

## Additions

- Adds commonjs module structure guidance.

## Changes

- Changes UpperCamelCase to PascalCase.
- Adds note about conventions of dollar sign prefixing jQuery references.

## Review

- @ascott1 
- @wpears 
- @mistergone

### CODE REVIEW

**Comment by wpears** [comment]
`modules.exports` should be `module.exports` at lines 128, 168, and 215.

**Comment by ascott1** [comment]
Other than @wpears's comment, this looks great. Update that and let's merge.

Should this be added to the README or just be linked from the JS style guide?

**Comment by contolini** [comment]
:+1:

**Comment by ascott1** [comment]
@anselmbradford do you want to fix those typos so this can be merged?

**Comment by anselmbradford** [comment]
Sure I can do that today. I wanted to post guidance on class modules that have private methods but there hasn't been any time this week. I can add that separately later though.

**Comment by anselmbradford** [comment]
Okay pushed update.

**Comment by ascott1** [comment]
:+1: Thanks @anselmbradford!

**Pull request merged**
