### PR TITLE
Accessibility updates

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
I broke Accessibility out into its own section and added some more information, including cribbing 18F's keyboard testing checklist with credit.

## Additions

- Added `accessibility.md`

## Changes

- Updated `markup.md` and `accessibility.md` to add more useful information about keyboard testing, setting languages.

### CODE REVIEW

**Comment by ascott1** [comment]
This is GREAT @KimberlyMunoz! A couple of very minor notes:

- Should we link to this from the README? It seems applicable in all sorts of contexts outside of markup.
- Should we include a link to @contolini's node-wcag project for automated accessibility testing?

**Comment by ascott1** [comment]
Merging, we can address the above questions at a later date.

**Comment by KimberlyMunoz** [comment]
Sorry about that Adam! I'll see about getting that second PR in!

**Comment by ascott1** [comment]
No problem! I just noticed this was sitting here and it was worth merging in as is.

**Pull request merged**
