### PR TITLE
Update README with full list of links

### PR DESCRIPTION
**Pull request by ascott1**
This adds any missing links to the TOC in the README, alphabetizes those links, adds a note about npm, and bumps this to 1.1.0 as there are several unpublished changes not in npm.

## Review

@cfpb/front-end-team-admin

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1:

**Comment by Scotchester** [comment]
This is not really a problem specific to this PR, but if that change log is going to be useful, it needs some fill-in work for things that weren't entered, and we should start including the version numbers.

**Comment by ascott1** [comment]
> This is not really a problem specific to this PR, but if that change log is going to be useful, it needs some fill-in work for things that weren't entered, and we should start including the version numbers.

Agreed. It's in a sad state.

**Comment by Scotchester** [comment]
Anyway, other than that, :+1:

**Pull request merged**
